"""Generate the antialiased 270-degree ring, without runtime trigonometry."""
from pathlib import Path
import math

target=Path(__file__).parents[1]/'arduino/BBQ-Control-V2/RingPixels.h'
pixels=[]
for y in range(6,228):
    for x in range(129,351):
        radius=math.hypot(x-240,y-114)
        alpha=min(1,5-abs(radius-103))
        if alpha<=0: continue
        angle=(math.degrees(math.atan2(y-114,x-240))-135)%360
        if angle>270: continue
        packed=(x-129)|((y-6)<<8)|(round(angle/270*255)<<16)|(round(alpha*255)<<24)
        pixels.append(packed)
target.write_text('#pragma once\n#include <stdint.h>\n// Generated by tools/generate_ring.py. x, y, angle, alpha in four bytes.\n'
                  'static const uint32_t RingPixels[]={\n'+
                  ',\n'.join(','.join('0x%08xu'%v for v in pixels[i:i+12]) for i in range(0,len(pixels),12))+'\n};\n')
print(f'{len(pixels)} ring pixels, {len(pixels)*4} flash bytes; no runtime geometry allocation')
